apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: seventy5test

spec:
  replicas: 1
  selector:
    matchLabels:
      app: seventy5test
  template:
    metadata:
      labels:
        app: seventy5test
    spec:
      containers:
        - name: seventy5test
          image: udayvarma007/seventy5-docker:${{ github.run_number }}
          env:
            - name: DATABASE_URL
              value: jdbc:sqlserver://seventy5-server.database.windows.net:1433;database=seventy;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryManagedIdentity
          ports:
            - containerPort: 8080



---

apiVersion: v1
kind: Service
metadata:
  name: java-webapp1-loadbalancer-service
  labels:
    app: seventy5test
spec:
  type: LoadBalancer
  selector:
    app: seventy5test
  ports:
    - port: 8080
      targetPort: 8080