name: Build and Deploy
on:
 workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Generate Maven Wrapper files
      run: mvn -N io.takari:maven:wrapper
    - name: Make Maven Wrapper executable
      run: chmod +x mvnw
    - name: Build JAR with cloud profile
      run: |
        ./mvnw clean package -Dspring.profiles.active=cloud
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: udayvarma007/seventy5-docker
        tags: ${{ github.run_number }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}